# Generated by Django 4.2.8 on 2025-11-04 10:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sanpham', '0001_initial'),
        ('Muahang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuGiaoDich',
            fields=[
                ('ma_giao_dich', models.AutoField(primary_key=True, serialize=False)),
                ('loai_giao_dich', models.CharField(choices=[('NHAP', 'Nhập kho'), ('XUAT', 'Xuất kho'), ('DIEU_CHINH', 'Điều chỉnh')], max_length=50, verbose_name='Loại giao dịch')),
                ('so_luong_thay_doi', models.IntegerField(verbose_name='Số lượng thay đổi')),
                ('ton_kho_sau_giao_dich', models.IntegerField(default=0, verbose_name='Tồn kho sau giao dịch')),
                ('thoi_gian_thuc_hien', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thực hiện')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('don_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Muahang.donhang', verbose_name='Đơn hàng liên quan')),
                ('ma_sp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sanpham.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Lịch sử giao dịch',
                'ordering': ['thoi_gian_thuc_hien'],
            },
        ),
        migrations.CreateModel(
            name='KhoHang',
            fields=[
                ('ma_kho_hang', models.CharField(default='KH0001', max_length=6, primary_key=True, serialize=False, verbose_name='Mã kho hàng')),
                ('so_luong_ton_kho', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng tồn kho')),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('ma_sp', models.ForeignKey(db_column='MaSP', on_delete=django.db.models.deletion.CASCADE, related_name='kho_hang', to='Sanpham.sanpham', verbose_name='Sản phẩm')),
            ],
        ),
    ]
