# Generated by Django 4.2.8 on 2025-11-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='Tintuc/')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-ngay_dang'],
            },
        ),
    ]
