# Generated by Django 4.2.8 on 2025-11-08 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('ma_danh_muc', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Mã danh mục')),
                ('ten_danh_muc', models.CharField(max_length=255, verbose_name='Tên danh mục')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('duong_dan', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Đường dẫn')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('ma_sp', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Mã sản phẩm')),
                ('gia_goc', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá gốc')),
                ('ty_le_giam_gia', models.IntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%'), (65, '65%'), (70, '75%'), (80, '80%'), (85, '85%'), (90, '90%'), (95, '95%'), (100, '100%')], default=0, verbose_name='Mã giảm giá (%)')),
                ('ten_sp', models.CharField(max_length=500, verbose_name='Tên sản phẩm')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('so_luong', models.IntegerField(verbose_name='Số lượng')),
                ('don_vi_tinh', models.CharField(blank=True, default='Cái', max_length=50, null=True, verbose_name='Đơn vị tính')),
                ('choi_2_nguoi', models.BooleanField(default=False, verbose_name='2 người')),
                ('choi_4_nguoi', models.BooleanField(default=False, verbose_name='4 người')),
                ('choi_tren_4_nguoi', models.BooleanField(default=False, verbose_name='Trên 4 người')),
                ('tuoi_tren_6', models.BooleanField(default=False, verbose_name='> 6 tuổi')),
                ('tuoi_tren_16', models.BooleanField(default=False, verbose_name='> 16 tuổi')),
                ('tuoi_tren_18', models.BooleanField(default=False, verbose_name='> 18 tuổi')),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh đại diện')),
                ('trang_thai', models.CharField(choices=[('CON_HANG', 'Còn hàng'), ('HET_HANG', 'Hết hàng')], default='CON_HANG', max_length=10, verbose_name='Trạng thái')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('danh_muc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sanpham.danhmuc', verbose_name='Danh mục')),
                ('san_pham_lien_quan', models.ManyToManyField(blank=True, to='Sanpham.sanpham', verbose_name='Sản phẩm liên quan')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='HinhAnhSanPham',
            fields=[
                ('ma_hinh_anh_sp', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Mã hình ảnh sản phẩm')),
                ('duong_dan', models.ImageField(upload_to='products_gallery/', verbose_name='Đường dẫn')),
                ('ghi_chu', models.CharField(default='Ảnh phụ', max_length=255, verbose_name='Ghi chú')),
                ('ma_sp', models.ForeignKey(db_column='ma_sp', on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh_phu', to='Sanpham.sanpham', verbose_name='Mã sản phẩm')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Hình ảnh sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='DanhGiaSanPham',
            fields=[
                ('ma_danh_gia', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Mã đánh giá')),
                ('diem_danh_gia', models.IntegerField(verbose_name='Điểm đánh giá')),
                ('binh_luan', models.TextField(blank=True, null=True, verbose_name='Bình luận')),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('ma_nguoi_dung', models.ForeignKey(db_column='ma_nguoi_dung', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mã người dùng')),
                ('ma_sp', models.ForeignKey(db_column='ma_sp', on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='Sanpham.sanpham', verbose_name='Mã sản phẩm')),
            ],
            options={
                'verbose_name': 'Đánh giá sản phẩm',
                'verbose_name_plural': 'Đánh giá sản phẩm',
            },
        ),
    ]
