# Generated by Django 4.2.8 on 2025-11-05 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('sdt', models.CharField(blank=True, max_length=15, null=True)),
                ('dia_chi', models.CharField(blank=True, max_length=255, null=True)),
                ('vai_tro', models.CharField(default='Khách hàng', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nguoidung', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
