# Generated by Django 4.2.8 on 2025-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taikhoan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='vai_tro',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
