# Generated by Django 4.2.8 on 2025-11-04 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dia_chi', models.TextField()),
                ('tinh', models.CharField(max_length=50)),
                ('phuong_xa', models.CharField(max_length=50)),
                ('ghi_chu', models.TextField(blank=True, default='')),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('phi_van_chuyen', models.IntegerField(default=0)),
                ('so_tien_duoc_giam', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trang_thai', models.CharField(default='Đang giao', max_length=50)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='TrangThaiDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.CharField(choices=[('Thanh cong', 'Thành công'), ('That bai', 'Thất bại')], max_length=50)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_trang_thai', to='Muahang.donhang')),
            ],
        ),
        migrations.CreateModel(
            name='GioHangItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('gio_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Muahang.giohang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Muahang.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='DonHangItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Muahang.donhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Muahang.sanpham')),
            ],
        ),
    ]
