# Generated by Django 4.2.8 on 2025-11-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muahang', '0002_alter_giohang_nguoi_dung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trangthaidonhang',
            name='noi_dung',
            field=models.CharField(choices=[('Nguoi ban da gui don', 'Người bán đã gửi đơn'), ('Thanh cong', 'Thành công'), ('That bai', 'Thất bại')], max_length=50),
        ),
    ]
