# Generated by Django 4.2.8 on 2025-11-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sanpham', '0001_initial'),
        ('Muahang', '0003_alter_trangthaidonhang_noi_dung'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='ma_voucher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donhang',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng (COD)'), ('VNPAY', 'Thẻ ATM (App bank)/ Thẻ tín dụng (Credit Card)/ Thẻ ghi nợ (Debit Card))'), ('ZALOPAY', 'Ví điện tử ZaloPay'), ('MOMO', 'Ví MoMo')], default='COD', max_length=10, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='phi_van_chuyen',
            field=models.IntegerField(default=30000),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai',
            field=models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('dang_giao', 'Đang giao'), ('da_giao', 'Đã giao'), ('that_bai', 'Thất bại')], default='cho_xac_nhan', max_length=50),
        ),
        migrations.AlterField(
            model_name='donhangitem',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sanpham.sanpham'),
        ),
        migrations.AlterField(
            model_name='giohangitem',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sanpham.sanpham'),
        ),
        migrations.AlterField(
            model_name='trangthaidonhang',
            name='noi_dung',
            field=models.CharField(choices=[('Cho xac nhan', 'Chờ xác nhận'), ('Dang giao', 'Đang giao'), ('Thanh cong', 'Thành công'), ('That bai', 'Thất bại')], max_length=50),
        ),
        migrations.DeleteModel(
            name='SanPham',
        ),
    ]
