# Generated by Django 4.2.25 on 2025-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CauHoiThuongGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cau_hoi', models.CharField(max_length=255, verbose_name='Câu hỏi')),
                ('cau_tra_loi', models.TextField(blank=True, null=True, verbose_name='Câu trả lời')),
                ('hien_thi', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Câu hỏi thường gặp',
                'verbose_name_plural': 'Danh sách câu hỏi thường gặp',
                'db_table': 'cau_hoi_thuong_gap',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
