# Generated by Django 4.2.8 on 2025-11-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lienhe', '0001_initial'),
    ]

    # 0001 đã tạo model CauHoiThuongGap và hiện không còn model FAQ trong trạng thái trước đó.
    # Để tránh lỗi state KeyError('Lienhe', 'faq') khi build project state,
    # biến migration này thành migration "trống" (no-op).
    operations = [
    ]
