# Generated by Django 4.2.25 on 2025-11-07 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YeuCauHoTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_yeu_cau', models.CharField(blank=True, max_length=20, unique=True)),
                ('ten_san_pham', models.CharField(blank=True, max_length=255)),
                ('loai_yeu_cau', models.CharField(choices=[('tu_van', 'Tư vấn'), ('khieu_nai', 'Khiếu nại'), ('ho_tro', 'Hỗ trợ')], default='tu_van', max_length=30)),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField(blank=True)),
                ('trang_thai', models.CharField(choices=[('cho_xu_ly', 'Chưa xử lý'), ('dang_xu_ly', 'Đang xử lý'), ('da_xu_ly', 'Đã xử lý'), ('dong', 'Đóng')], default='cho_xu_ly', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('cap_nhat_luc', models.DateTimeField(auto_now=True)),
                ('muc_do_uu_tien', models.IntegerField(default=3)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeu_cau_ho_tro', to=settings.AUTH_USER_MODEL)),
                ('nguoi_ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yeu_cau_duoc_giao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu hỗ trợ',
                'verbose_name_plural': 'Danh sách yêu cầu hỗ trợ',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='TinNhanHoTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('noi_bo', models.BooleanField(default=False)),
                ('nguoi_gui', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('yeu_cau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to='Hotro.yeucauhotro')),
            ],
            options={
                'verbose_name': 'Tin nhắn hỗ trợ',
                'verbose_name_plural': 'Tin nhắn hỗ trợ',
                'ordering': ['ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='HoSoNguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vai_tro', models.CharField(choices=[('khach_hang', 'Khách hàng'), ('nguoi_ban', 'Người bán'), ('quan_tri', 'Quản trị')], default='khach_hang', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ho_so', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
