# Generated by Django 4.2.25 on 2025-11-07 16:38

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_bao_cao', models.CharField(max_length=20, unique=True)),
                ('loai_bao_cao', models.CharField(default='doanhthu', max_length=50)),
                ('ngay_bao_cao', models.DateField(default=django.utils.timezone.now)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('tong_khach_hang', models.IntegerField(default=0)),
                ('so_don_hang', models.IntegerField(default=0)),
                ('tong_doanh_thu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('loi_nhuan', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('data_time_series', models.JSONField(blank=True, null=True)),
                ('data_top_products', models.JSONField(blank=True, null=True)),
                ('data_complaints', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bao_cao',
                'ordering': ['-ngay_bao_cao'],
            },
        ),
    ]
